name: Test csb-validator

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.11", "3.12"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[trusted-node]"  # editable mode with optional extras
          pip install -r requirements.txt
          pip install pytest pytest-cov black flake8 mypy

      - name: Check code formatting with Black
        run: black --check csb_validator tests

      - name: Lint with flake8
        run: flake8 csb_validator tests

      - name: Static type check with mypy
        run: mypy csb_validator

      - name: Run tests with coverage
        run: pytest --cov=csb_validator --cov-report=term-missing
